---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен успешно авторизоваться на сайте
  - Пользователь должен иметь возможность запустить игру с ботом, другом и другим игроком
  - Пользователь должен иметь возможность видеть код соперника
  - Пользователь может выбрать игру по уровню сложности
  - Каждый игрок имеет кнопку "check" для проверки своего решения
  - Оба игрока видят два редактора: слева - свой редактор, справа - соперника
  - Игра высвечивается как "доступная для подключения" у других пользователей
  - Когда оба игрока вышли, игра считается полностью законченной и удаляется из памяти
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - На сайте должна быть табилца рейтинга пользователей
  - На сайте должна быть личная статистика побед и поражений пользователя
